apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: 'dev'
          # matchExpressions:
          #   - key: environment
          #     operator: In
          #     values:
          #       - "dev"
  template:
    metadata:
      name: '{{name}}-bootstrap-addons'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/peishuli/gitops-repo'
        path: 'addons'
        targetRevision: 'main'
        directory:
          recurse: true
      destination:
        namespace: 'argocd'
        name: {{ name }}
      syncPolicy:
        automated: {}
